name: ui
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono #If you change this name the font will show up in Goldens
      fonts:
        - asset: packages/ui/fonts/RobotoMono-Medium.ttf
  assets:
    - images/